import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import { ThemeProvider } from "@/components/theme-provider";
import HeaderMenu from "@/components/headerMenu/page";
import CurrentTime from "@/components/CurrentTime/page";
// const inter = Inter({ subsets: ["latin"] });
import styles from './page.module.css'
import { FaLinkedinIn } from "react-icons/fa";
import NameAnimation from "@/components/nameAnimation/page";
import LightDarkToggle from "@/components/LightDarkToggle/page";
import SmoothScroll from "@/components/smoothScroll/page";
import PageTransitionEffect from "@/components/PageTransEffect/page";
import {TransitionProvider} from "./context/TransitionContext"
import Transition from "./context/Transition"
import Link from "next/link";

export const metadata: Metadata = {
  title: "Alex Hong - Next.js Portfolio",
  description: "Alex Hong - Next.js Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // NOTES - suppressHydrationWarning
    <html lang="en" id="htmlId" suppressHydrationWarning> 
      <body 
        // className={inter.className}
      >
{/* <Link style={{color: "black"}}scroll={false} href="/pageOne">PageOne</Link>
<Link style={{color: "black"}}scroll={false} href="/pageTwo">PageTwo</Link> */}


        {/* <PageTransitionEffect> */}
        {/* <TransitionProvider>
        <Transition> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* <nav className="" style={{top: "100px", position: 'absolute', zIndex: 10005}}>
            <div className="">
              <MainNav />
            </div>
          </nav> */}

          <div 
            // style={{mixBlendMode: 'exclusion'}} // Set : mix-blend-mode
          >
            {/* <LightDarkToggle /> */}
            
            <HeaderMenu />
            <NameAnimation />

            <SmoothScroll>
              {/* <PageTransitionEffect> */}
              
                {children}
              
              {/* </PageTransitionEffect> */}
            </SmoothScroll>

            {/* LINKEDIN */}
            <div className={styles.linkedin_container}>
              <a href="https://www.linkedin.com/in/young-alex-hong/" target="_blank">
                <FaLinkedinIn />
                <span></span>
                <p>Alex-Y-Hong/</p>
              </a>
            </div>

            <CurrentTime />
          </div>

        </ThemeProvider>
        {/* </PageTransitionEffect> */}
        {/* </Transition>
        </TransitionProvider> */}
      </body>
    </html>
  );
}

// bluish black
// hsl(217.2, 32.6%, 17.5%)
// #020817

/*
suppressHydrationWarning :
https://github.com/shadcn/next-contentlayer/issues/7
*/


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import MainNav from "@/components/MainNav";
// import { ThemeProvider } from "@/components/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Ticket Application",
//   description: "Generated by Clarity Coders",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="dark"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <nav className="flex flex-col items-center border-b mb-5 px-5 py-3">
//             <div className="max-w-6xl w-full">
//               <MainNav />
//             </div>
//           </nav>
//           <main className="flex flex-col items-center">
//             <div className="max-w-6xl w-full">{children}</div>
//           </main>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
